// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package domain

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Domain struct {
	pulumi.CustomResourceState

	Admins DomainAdminArrayOutput `pulumi:"admins"`
	// Should the domain autorenew
	Autorenew pulumi.BoolPtrOutput     `pulumi:"autorenew"`
	Billings  DomainBillingArrayOutput `pulumi:"billings"`
	// The FQDN of the domain
	Name pulumi.StringOutput `pulumi:"name"`
	// A list of nameservers for the domain
	Nameservers pulumi.StringArrayOutput `pulumi:"nameservers"`
	Owners      DomainOwnerArrayOutput   `pulumi:"owners"`
	Teches      DomainTechArrayOutput    `pulumi:"teches"`
}

// NewDomain registers a new resource with the given unique name, arguments, and options.
func NewDomain(ctx *pulumi.Context,
	name string, args *DomainArgs, opts ...pulumi.ResourceOption) (*Domain, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Admins == nil {
		return nil, errors.New("invalid value for required argument 'Admins'")
	}
	if args.Billings == nil {
		return nil, errors.New("invalid value for required argument 'Billings'")
	}
	if args.Owners == nil {
		return nil, errors.New("invalid value for required argument 'Owners'")
	}
	if args.Teches == nil {
		return nil, errors.New("invalid value for required argument 'Teches'")
	}
	var resource Domain
	err := ctx.RegisterResource("gandi:domain/domain:Domain", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDomain gets an existing Domain resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDomain(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DomainState, opts ...pulumi.ResourceOption) (*Domain, error) {
	var resource Domain
	err := ctx.ReadResource("gandi:domain/domain:Domain", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Domain resources.
type domainState struct {
	Admins []DomainAdmin `pulumi:"admins"`
	// Should the domain autorenew
	Autorenew *bool           `pulumi:"autorenew"`
	Billings  []DomainBilling `pulumi:"billings"`
	// The FQDN of the domain
	Name *string `pulumi:"name"`
	// A list of nameservers for the domain
	Nameservers []string      `pulumi:"nameservers"`
	Owners      []DomainOwner `pulumi:"owners"`
	Teches      []DomainTech  `pulumi:"teches"`
}

type DomainState struct {
	Admins DomainAdminArrayInput
	// Should the domain autorenew
	Autorenew pulumi.BoolPtrInput
	Billings  DomainBillingArrayInput
	// The FQDN of the domain
	Name pulumi.StringPtrInput
	// A list of nameservers for the domain
	Nameservers pulumi.StringArrayInput
	Owners      DomainOwnerArrayInput
	Teches      DomainTechArrayInput
}

func (DomainState) ElementType() reflect.Type {
	return reflect.TypeOf((*domainState)(nil)).Elem()
}

type domainArgs struct {
	Admins []DomainAdmin `pulumi:"admins"`
	// Should the domain autorenew
	Autorenew *bool           `pulumi:"autorenew"`
	Billings  []DomainBilling `pulumi:"billings"`
	// The FQDN of the domain
	Name *string `pulumi:"name"`
	// A list of nameservers for the domain
	Nameservers []string      `pulumi:"nameservers"`
	Owners      []DomainOwner `pulumi:"owners"`
	Teches      []DomainTech  `pulumi:"teches"`
}

// The set of arguments for constructing a Domain resource.
type DomainArgs struct {
	Admins DomainAdminArrayInput
	// Should the domain autorenew
	Autorenew pulumi.BoolPtrInput
	Billings  DomainBillingArrayInput
	// The FQDN of the domain
	Name pulumi.StringPtrInput
	// A list of nameservers for the domain
	Nameservers pulumi.StringArrayInput
	Owners      DomainOwnerArrayInput
	Teches      DomainTechArrayInput
}

func (DomainArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*domainArgs)(nil)).Elem()
}

type DomainInput interface {
	pulumi.Input

	ToDomainOutput() DomainOutput
	ToDomainOutputWithContext(ctx context.Context) DomainOutput
}

func (*Domain) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (i *Domain) ToDomainOutput() DomainOutput {
	return i.ToDomainOutputWithContext(context.Background())
}

func (i *Domain) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainOutput)
}

// DomainArrayInput is an input type that accepts DomainArray and DomainArrayOutput values.
// You can construct a concrete instance of `DomainArrayInput` via:
//
//          DomainArray{ DomainArgs{...} }
type DomainArrayInput interface {
	pulumi.Input

	ToDomainArrayOutput() DomainArrayOutput
	ToDomainArrayOutputWithContext(context.Context) DomainArrayOutput
}

type DomainArray []DomainInput

func (DomainArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Domain)(nil)).Elem()
}

func (i DomainArray) ToDomainArrayOutput() DomainArrayOutput {
	return i.ToDomainArrayOutputWithContext(context.Background())
}

func (i DomainArray) ToDomainArrayOutputWithContext(ctx context.Context) DomainArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainArrayOutput)
}

// DomainMapInput is an input type that accepts DomainMap and DomainMapOutput values.
// You can construct a concrete instance of `DomainMapInput` via:
//
//          DomainMap{ "key": DomainArgs{...} }
type DomainMapInput interface {
	pulumi.Input

	ToDomainMapOutput() DomainMapOutput
	ToDomainMapOutputWithContext(context.Context) DomainMapOutput
}

type DomainMap map[string]DomainInput

func (DomainMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Domain)(nil)).Elem()
}

func (i DomainMap) ToDomainMapOutput() DomainMapOutput {
	return i.ToDomainMapOutputWithContext(context.Background())
}

func (i DomainMap) ToDomainMapOutputWithContext(ctx context.Context) DomainMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DomainMapOutput)
}

type DomainOutput struct{ *pulumi.OutputState }

func (DomainOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Domain)(nil)).Elem()
}

func (o DomainOutput) ToDomainOutput() DomainOutput {
	return o
}

func (o DomainOutput) ToDomainOutputWithContext(ctx context.Context) DomainOutput {
	return o
}

type DomainArrayOutput struct{ *pulumi.OutputState }

func (DomainArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Domain)(nil)).Elem()
}

func (o DomainArrayOutput) ToDomainArrayOutput() DomainArrayOutput {
	return o
}

func (o DomainArrayOutput) ToDomainArrayOutputWithContext(ctx context.Context) DomainArrayOutput {
	return o
}

func (o DomainArrayOutput) Index(i pulumi.IntInput) DomainOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Domain {
		return vs[0].([]*Domain)[vs[1].(int)]
	}).(DomainOutput)
}

type DomainMapOutput struct{ *pulumi.OutputState }

func (DomainMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Domain)(nil)).Elem()
}

func (o DomainMapOutput) ToDomainMapOutput() DomainMapOutput {
	return o
}

func (o DomainMapOutput) ToDomainMapOutputWithContext(ctx context.Context) DomainMapOutput {
	return o
}

func (o DomainMapOutput) MapIndex(k pulumi.StringInput) DomainOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Domain {
		return vs[0].(map[string]*Domain)[vs[1].(string)]
	}).(DomainOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DomainInput)(nil)).Elem(), &Domain{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainArrayInput)(nil)).Elem(), DomainArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DomainMapInput)(nil)).Elem(), DomainMap{})
	pulumi.RegisterOutputType(DomainOutput{})
	pulumi.RegisterOutputType(DomainArrayOutput{})
	pulumi.RegisterOutputType(DomainMapOutput{})
}
