# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('gandi')


class _ExportableConfig(types.ModuleType):
    @property
    def dry_run(self) -> Optional[bool]:
        """
        Prevent the Domain provider from taking certain actions
        """
        return __config__.get_bool('dryRun')

    @property
    def key(self) -> Optional[str]:
        """
        A Gandi API key
        """
        return __config__.get('key')

    @property
    def sharing_id(self) -> Optional[str]:
        """
        A Gandi Sharing ID
        """
        return __config__.get('sharingId')

    @property
    def url(self) -> Optional[str]:
        """
        The Gandi API URL
        """
        return __config__.get('url')

