# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = [
    'DomainAdminArgs',
    'DomainBillingArgs',
    'DomainOwnerArgs',
    'DomainTechArgs',
]

@pulumi.input_type
class DomainAdminArgs:
    def __init__(__self__, *,
                 city: pulumi.Input[str],
                 country: pulumi.Input[str],
                 email: pulumi.Input[str],
                 family_name: pulumi.Input[str],
                 given_name: pulumi.Input[str],
                 phone: pulumi.Input[str],
                 street_addr: pulumi.Input[str],
                 type: pulumi.Input[str],
                 zip: pulumi.Input[str],
                 data_obfuscated: Optional[pulumi.Input[bool]] = None,
                 extra_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 mail_obfuscated: Optional[pulumi.Input[bool]] = None,
                 organisation: Optional[pulumi.Input[str]] = None,
                 state: Optional[pulumi.Input[str]] = None):
        pulumi.set(__self__, "city", city)
        pulumi.set(__self__, "country", country)
        pulumi.set(__self__, "email", email)
        pulumi.set(__self__, "family_name", family_name)
        pulumi.set(__self__, "given_name", given_name)
        pulumi.set(__self__, "phone", phone)
        pulumi.set(__self__, "street_addr", street_addr)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "zip", zip)
        if data_obfuscated is not None:
            pulumi.set(__self__, "data_obfuscated", data_obfuscated)
        if extra_parameters is not None:
            pulumi.set(__self__, "extra_parameters", extra_parameters)
        if mail_obfuscated is not None:
            pulumi.set(__self__, "mail_obfuscated", mail_obfuscated)
        if organisation is not None:
            pulumi.set(__self__, "organisation", organisation)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @property
    @pulumi.getter
    def city(self) -> pulumi.Input[str]:
        return pulumi.get(self, "city")

    @city.setter
    def city(self, value: pulumi.Input[str]):
        pulumi.set(self, "city", value)

    @property
    @pulumi.getter
    def country(self) -> pulumi.Input[str]:
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: pulumi.Input[str]):
        pulumi.set(self, "country", value)

    @property
    @pulumi.getter
    def email(self) -> pulumi.Input[str]:
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[str]):
        pulumi.set(self, "email", value)

    @property
    @pulumi.getter(name="familyName")
    def family_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "family_name")

    @family_name.setter
    def family_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "family_name", value)

    @property
    @pulumi.getter(name="givenName")
    def given_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "given_name")

    @given_name.setter
    def given_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "given_name", value)

    @property
    @pulumi.getter
    def phone(self) -> pulumi.Input[str]:
        return pulumi.get(self, "phone")

    @phone.setter
    def phone(self, value: pulumi.Input[str]):
        pulumi.set(self, "phone", value)

    @property
    @pulumi.getter(name="streetAddr")
    def street_addr(self) -> pulumi.Input[str]:
        return pulumi.get(self, "street_addr")

    @street_addr.setter
    def street_addr(self, value: pulumi.Input[str]):
        pulumi.set(self, "street_addr", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def zip(self) -> pulumi.Input[str]:
        return pulumi.get(self, "zip")

    @zip.setter
    def zip(self, value: pulumi.Input[str]):
        pulumi.set(self, "zip", value)

    @property
    @pulumi.getter(name="dataObfuscated")
    def data_obfuscated(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "data_obfuscated")

    @data_obfuscated.setter
    def data_obfuscated(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "data_obfuscated", value)

    @property
    @pulumi.getter(name="extraParameters")
    def extra_parameters(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        return pulumi.get(self, "extra_parameters")

    @extra_parameters.setter
    def extra_parameters(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "extra_parameters", value)

    @property
    @pulumi.getter(name="mailObfuscated")
    def mail_obfuscated(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "mail_obfuscated")

    @mail_obfuscated.setter
    def mail_obfuscated(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "mail_obfuscated", value)

    @property
    @pulumi.getter
    def organisation(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "organisation")

    @organisation.setter
    def organisation(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "organisation", value)

    @property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "state", value)


@pulumi.input_type
class DomainBillingArgs:
    def __init__(__self__, *,
                 city: pulumi.Input[str],
                 country: pulumi.Input[str],
                 email: pulumi.Input[str],
                 family_name: pulumi.Input[str],
                 given_name: pulumi.Input[str],
                 phone: pulumi.Input[str],
                 street_addr: pulumi.Input[str],
                 type: pulumi.Input[str],
                 zip: pulumi.Input[str],
                 data_obfuscated: Optional[pulumi.Input[bool]] = None,
                 extra_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 mail_obfuscated: Optional[pulumi.Input[bool]] = None,
                 organisation: Optional[pulumi.Input[str]] = None,
                 state: Optional[pulumi.Input[str]] = None):
        pulumi.set(__self__, "city", city)
        pulumi.set(__self__, "country", country)
        pulumi.set(__self__, "email", email)
        pulumi.set(__self__, "family_name", family_name)
        pulumi.set(__self__, "given_name", given_name)
        pulumi.set(__self__, "phone", phone)
        pulumi.set(__self__, "street_addr", street_addr)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "zip", zip)
        if data_obfuscated is not None:
            pulumi.set(__self__, "data_obfuscated", data_obfuscated)
        if extra_parameters is not None:
            pulumi.set(__self__, "extra_parameters", extra_parameters)
        if mail_obfuscated is not None:
            pulumi.set(__self__, "mail_obfuscated", mail_obfuscated)
        if organisation is not None:
            pulumi.set(__self__, "organisation", organisation)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @property
    @pulumi.getter
    def city(self) -> pulumi.Input[str]:
        return pulumi.get(self, "city")

    @city.setter
    def city(self, value: pulumi.Input[str]):
        pulumi.set(self, "city", value)

    @property
    @pulumi.getter
    def country(self) -> pulumi.Input[str]:
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: pulumi.Input[str]):
        pulumi.set(self, "country", value)

    @property
    @pulumi.getter
    def email(self) -> pulumi.Input[str]:
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[str]):
        pulumi.set(self, "email", value)

    @property
    @pulumi.getter(name="familyName")
    def family_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "family_name")

    @family_name.setter
    def family_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "family_name", value)

    @property
    @pulumi.getter(name="givenName")
    def given_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "given_name")

    @given_name.setter
    def given_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "given_name", value)

    @property
    @pulumi.getter
    def phone(self) -> pulumi.Input[str]:
        return pulumi.get(self, "phone")

    @phone.setter
    def phone(self, value: pulumi.Input[str]):
        pulumi.set(self, "phone", value)

    @property
    @pulumi.getter(name="streetAddr")
    def street_addr(self) -> pulumi.Input[str]:
        return pulumi.get(self, "street_addr")

    @street_addr.setter
    def street_addr(self, value: pulumi.Input[str]):
        pulumi.set(self, "street_addr", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def zip(self) -> pulumi.Input[str]:
        return pulumi.get(self, "zip")

    @zip.setter
    def zip(self, value: pulumi.Input[str]):
        pulumi.set(self, "zip", value)

    @property
    @pulumi.getter(name="dataObfuscated")
    def data_obfuscated(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "data_obfuscated")

    @data_obfuscated.setter
    def data_obfuscated(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "data_obfuscated", value)

    @property
    @pulumi.getter(name="extraParameters")
    def extra_parameters(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        return pulumi.get(self, "extra_parameters")

    @extra_parameters.setter
    def extra_parameters(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "extra_parameters", value)

    @property
    @pulumi.getter(name="mailObfuscated")
    def mail_obfuscated(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "mail_obfuscated")

    @mail_obfuscated.setter
    def mail_obfuscated(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "mail_obfuscated", value)

    @property
    @pulumi.getter
    def organisation(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "organisation")

    @organisation.setter
    def organisation(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "organisation", value)

    @property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "state", value)


@pulumi.input_type
class DomainOwnerArgs:
    def __init__(__self__, *,
                 city: pulumi.Input[str],
                 country: pulumi.Input[str],
                 email: pulumi.Input[str],
                 family_name: pulumi.Input[str],
                 given_name: pulumi.Input[str],
                 phone: pulumi.Input[str],
                 street_addr: pulumi.Input[str],
                 type: pulumi.Input[str],
                 zip: pulumi.Input[str],
                 data_obfuscated: Optional[pulumi.Input[bool]] = None,
                 extra_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 mail_obfuscated: Optional[pulumi.Input[bool]] = None,
                 organisation: Optional[pulumi.Input[str]] = None,
                 state: Optional[pulumi.Input[str]] = None):
        pulumi.set(__self__, "city", city)
        pulumi.set(__self__, "country", country)
        pulumi.set(__self__, "email", email)
        pulumi.set(__self__, "family_name", family_name)
        pulumi.set(__self__, "given_name", given_name)
        pulumi.set(__self__, "phone", phone)
        pulumi.set(__self__, "street_addr", street_addr)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "zip", zip)
        if data_obfuscated is not None:
            pulumi.set(__self__, "data_obfuscated", data_obfuscated)
        if extra_parameters is not None:
            pulumi.set(__self__, "extra_parameters", extra_parameters)
        if mail_obfuscated is not None:
            pulumi.set(__self__, "mail_obfuscated", mail_obfuscated)
        if organisation is not None:
            pulumi.set(__self__, "organisation", organisation)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @property
    @pulumi.getter
    def city(self) -> pulumi.Input[str]:
        return pulumi.get(self, "city")

    @city.setter
    def city(self, value: pulumi.Input[str]):
        pulumi.set(self, "city", value)

    @property
    @pulumi.getter
    def country(self) -> pulumi.Input[str]:
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: pulumi.Input[str]):
        pulumi.set(self, "country", value)

    @property
    @pulumi.getter
    def email(self) -> pulumi.Input[str]:
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[str]):
        pulumi.set(self, "email", value)

    @property
    @pulumi.getter(name="familyName")
    def family_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "family_name")

    @family_name.setter
    def family_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "family_name", value)

    @property
    @pulumi.getter(name="givenName")
    def given_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "given_name")

    @given_name.setter
    def given_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "given_name", value)

    @property
    @pulumi.getter
    def phone(self) -> pulumi.Input[str]:
        return pulumi.get(self, "phone")

    @phone.setter
    def phone(self, value: pulumi.Input[str]):
        pulumi.set(self, "phone", value)

    @property
    @pulumi.getter(name="streetAddr")
    def street_addr(self) -> pulumi.Input[str]:
        return pulumi.get(self, "street_addr")

    @street_addr.setter
    def street_addr(self, value: pulumi.Input[str]):
        pulumi.set(self, "street_addr", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def zip(self) -> pulumi.Input[str]:
        return pulumi.get(self, "zip")

    @zip.setter
    def zip(self, value: pulumi.Input[str]):
        pulumi.set(self, "zip", value)

    @property
    @pulumi.getter(name="dataObfuscated")
    def data_obfuscated(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "data_obfuscated")

    @data_obfuscated.setter
    def data_obfuscated(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "data_obfuscated", value)

    @property
    @pulumi.getter(name="extraParameters")
    def extra_parameters(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        return pulumi.get(self, "extra_parameters")

    @extra_parameters.setter
    def extra_parameters(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "extra_parameters", value)

    @property
    @pulumi.getter(name="mailObfuscated")
    def mail_obfuscated(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "mail_obfuscated")

    @mail_obfuscated.setter
    def mail_obfuscated(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "mail_obfuscated", value)

    @property
    @pulumi.getter
    def organisation(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "organisation")

    @organisation.setter
    def organisation(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "organisation", value)

    @property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "state", value)


@pulumi.input_type
class DomainTechArgs:
    def __init__(__self__, *,
                 city: pulumi.Input[str],
                 country: pulumi.Input[str],
                 email: pulumi.Input[str],
                 family_name: pulumi.Input[str],
                 given_name: pulumi.Input[str],
                 phone: pulumi.Input[str],
                 street_addr: pulumi.Input[str],
                 type: pulumi.Input[str],
                 zip: pulumi.Input[str],
                 data_obfuscated: Optional[pulumi.Input[bool]] = None,
                 extra_parameters: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]] = None,
                 mail_obfuscated: Optional[pulumi.Input[bool]] = None,
                 organisation: Optional[pulumi.Input[str]] = None,
                 state: Optional[pulumi.Input[str]] = None):
        pulumi.set(__self__, "city", city)
        pulumi.set(__self__, "country", country)
        pulumi.set(__self__, "email", email)
        pulumi.set(__self__, "family_name", family_name)
        pulumi.set(__self__, "given_name", given_name)
        pulumi.set(__self__, "phone", phone)
        pulumi.set(__self__, "street_addr", street_addr)
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "zip", zip)
        if data_obfuscated is not None:
            pulumi.set(__self__, "data_obfuscated", data_obfuscated)
        if extra_parameters is not None:
            pulumi.set(__self__, "extra_parameters", extra_parameters)
        if mail_obfuscated is not None:
            pulumi.set(__self__, "mail_obfuscated", mail_obfuscated)
        if organisation is not None:
            pulumi.set(__self__, "organisation", organisation)
        if state is not None:
            pulumi.set(__self__, "state", state)

    @property
    @pulumi.getter
    def city(self) -> pulumi.Input[str]:
        return pulumi.get(self, "city")

    @city.setter
    def city(self, value: pulumi.Input[str]):
        pulumi.set(self, "city", value)

    @property
    @pulumi.getter
    def country(self) -> pulumi.Input[str]:
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: pulumi.Input[str]):
        pulumi.set(self, "country", value)

    @property
    @pulumi.getter
    def email(self) -> pulumi.Input[str]:
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[str]):
        pulumi.set(self, "email", value)

    @property
    @pulumi.getter(name="familyName")
    def family_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "family_name")

    @family_name.setter
    def family_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "family_name", value)

    @property
    @pulumi.getter(name="givenName")
    def given_name(self) -> pulumi.Input[str]:
        return pulumi.get(self, "given_name")

    @given_name.setter
    def given_name(self, value: pulumi.Input[str]):
        pulumi.set(self, "given_name", value)

    @property
    @pulumi.getter
    def phone(self) -> pulumi.Input[str]:
        return pulumi.get(self, "phone")

    @phone.setter
    def phone(self, value: pulumi.Input[str]):
        pulumi.set(self, "phone", value)

    @property
    @pulumi.getter(name="streetAddr")
    def street_addr(self) -> pulumi.Input[str]:
        return pulumi.get(self, "street_addr")

    @street_addr.setter
    def street_addr(self, value: pulumi.Input[str]):
        pulumi.set(self, "street_addr", value)

    @property
    @pulumi.getter
    def type(self) -> pulumi.Input[str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[str]):
        pulumi.set(self, "type", value)

    @property
    @pulumi.getter
    def zip(self) -> pulumi.Input[str]:
        return pulumi.get(self, "zip")

    @zip.setter
    def zip(self, value: pulumi.Input[str]):
        pulumi.set(self, "zip", value)

    @property
    @pulumi.getter(name="dataObfuscated")
    def data_obfuscated(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "data_obfuscated")

    @data_obfuscated.setter
    def data_obfuscated(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "data_obfuscated", value)

    @property
    @pulumi.getter(name="extraParameters")
    def extra_parameters(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]:
        return pulumi.get(self, "extra_parameters")

    @extra_parameters.setter
    def extra_parameters(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[str]]]]):
        pulumi.set(self, "extra_parameters", value)

    @property
    @pulumi.getter(name="mailObfuscated")
    def mail_obfuscated(self) -> Optional[pulumi.Input[bool]]:
        return pulumi.get(self, "mail_obfuscated")

    @mail_obfuscated.setter
    def mail_obfuscated(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "mail_obfuscated", value)

    @property
    @pulumi.getter
    def organisation(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "organisation")

    @organisation.setter
    def organisation(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "organisation", value)

    @property
    @pulumi.getter
    def state(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "state")

    @state.setter
    def state(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "state", value)


