# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

__all__ = ['MailboxArgs', 'Mailbox']

@pulumi.input_type
class MailboxArgs:
    def __init__(__self__, *,
                 domain: pulumi.Input[str],
                 login: pulumi.Input[str],
                 password: pulumi.Input[str],
                 aliases: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 mailbox_type: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Mailbox resource.
        :param pulumi.Input[str] domain: Domain name
        :param pulumi.Input[str] login: Login
        :param pulumi.Input[str] password: Password
        :param pulumi.Input[Sequence[pulumi.Input[str]]] aliases: Aliases for email
        :param pulumi.Input[str] mailbox_type: Mailbox type
        """
        pulumi.set(__self__, "domain", domain)
        pulumi.set(__self__, "login", login)
        pulumi.set(__self__, "password", password)
        if aliases is not None:
            pulumi.set(__self__, "aliases", aliases)
        if mailbox_type is not None:
            pulumi.set(__self__, "mailbox_type", mailbox_type)

    @property
    @pulumi.getter
    def domain(self) -> pulumi.Input[str]:
        """
        Domain name
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[str]):
        pulumi.set(self, "domain", value)

    @property
    @pulumi.getter
    def login(self) -> pulumi.Input[str]:
        """
        Login
        """
        return pulumi.get(self, "login")

    @login.setter
    def login(self, value: pulumi.Input[str]):
        pulumi.set(self, "login", value)

    @property
    @pulumi.getter
    def password(self) -> pulumi.Input[str]:
        """
        Password
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: pulumi.Input[str]):
        pulumi.set(self, "password", value)

    @property
    @pulumi.getter
    def aliases(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Aliases for email
        """
        return pulumi.get(self, "aliases")

    @aliases.setter
    def aliases(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "aliases", value)

    @property
    @pulumi.getter(name="mailboxType")
    def mailbox_type(self) -> Optional[pulumi.Input[str]]:
        """
        Mailbox type
        """
        return pulumi.get(self, "mailbox_type")

    @mailbox_type.setter
    def mailbox_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "mailbox_type", value)


@pulumi.input_type
class _MailboxState:
    def __init__(__self__, *,
                 aliases: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 login: Optional[pulumi.Input[str]] = None,
                 mailbox_type: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering Mailbox resources.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] aliases: Aliases for email
        :param pulumi.Input[str] domain: Domain name
        :param pulumi.Input[str] login: Login
        :param pulumi.Input[str] mailbox_type: Mailbox type
        :param pulumi.Input[str] password: Password
        """
        if aliases is not None:
            pulumi.set(__self__, "aliases", aliases)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if login is not None:
            pulumi.set(__self__, "login", login)
        if mailbox_type is not None:
            pulumi.set(__self__, "mailbox_type", mailbox_type)
        if password is not None:
            pulumi.set(__self__, "password", password)

    @property
    @pulumi.getter
    def aliases(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Aliases for email
        """
        return pulumi.get(self, "aliases")

    @aliases.setter
    def aliases(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "aliases", value)

    @property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input[str]]:
        """
        Domain name
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "domain", value)

    @property
    @pulumi.getter
    def login(self) -> Optional[pulumi.Input[str]]:
        """
        Login
        """
        return pulumi.get(self, "login")

    @login.setter
    def login(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "login", value)

    @property
    @pulumi.getter(name="mailboxType")
    def mailbox_type(self) -> Optional[pulumi.Input[str]]:
        """
        Mailbox type
        """
        return pulumi.get(self, "mailbox_type")

    @mailbox_type.setter
    def mailbox_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "mailbox_type", value)

    @property
    @pulumi.getter
    def password(self) -> Optional[pulumi.Input[str]]:
        """
        Password
        """
        return pulumi.get(self, "password")

    @password.setter
    def password(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "password", value)


class Mailbox(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 aliases: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 login: Optional[pulumi.Input[str]] = None,
                 mailbox_type: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a Mailbox resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] aliases: Aliases for email
        :param pulumi.Input[str] domain: Domain name
        :param pulumi.Input[str] login: Login
        :param pulumi.Input[str] mailbox_type: Mailbox type
        :param pulumi.Input[str] password: Password
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: MailboxArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Mailbox resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param MailboxArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(MailboxArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 aliases: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 domain: Optional[pulumi.Input[str]] = None,
                 login: Optional[pulumi.Input[str]] = None,
                 mailbox_type: Optional[pulumi.Input[str]] = None,
                 password: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = MailboxArgs.__new__(MailboxArgs)

            __props__.__dict__["aliases"] = aliases
            if domain is None and not opts.urn:
                raise TypeError("Missing required property 'domain'")
            __props__.__dict__["domain"] = domain
            if login is None and not opts.urn:
                raise TypeError("Missing required property 'login'")
            __props__.__dict__["login"] = login
            __props__.__dict__["mailbox_type"] = mailbox_type
            if password is None and not opts.urn:
                raise TypeError("Missing required property 'password'")
            __props__.__dict__["password"] = password
        super(Mailbox, __self__).__init__(
            'gandi:email/mailbox:Mailbox',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            aliases: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
            domain: Optional[pulumi.Input[str]] = None,
            login: Optional[pulumi.Input[str]] = None,
            mailbox_type: Optional[pulumi.Input[str]] = None,
            password: Optional[pulumi.Input[str]] = None) -> 'Mailbox':
        """
        Get an existing Mailbox resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] aliases: Aliases for email
        :param pulumi.Input[str] domain: Domain name
        :param pulumi.Input[str] login: Login
        :param pulumi.Input[str] mailbox_type: Mailbox type
        :param pulumi.Input[str] password: Password
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _MailboxState.__new__(_MailboxState)

        __props__.__dict__["aliases"] = aliases
        __props__.__dict__["domain"] = domain
        __props__.__dict__["login"] = login
        __props__.__dict__["mailbox_type"] = mailbox_type
        __props__.__dict__["password"] = password
        return Mailbox(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def aliases(self) -> pulumi.Output[Optional[Sequence[str]]]:
        """
        Aliases for email
        """
        return pulumi.get(self, "aliases")

    @property
    @pulumi.getter
    def domain(self) -> pulumi.Output[str]:
        """
        Domain name
        """
        return pulumi.get(self, "domain")

    @property
    @pulumi.getter
    def login(self) -> pulumi.Output[str]:
        """
        Login
        """
        return pulumi.get(self, "login")

    @property
    @pulumi.getter(name="mailboxType")
    def mailbox_type(self) -> pulumi.Output[Optional[str]]:
        """
        Mailbox type
        """
        return pulumi.get(self, "mailbox_type")

    @property
    @pulumi.getter
    def password(self) -> pulumi.Output[str]:
        """
        Password
        """
        return pulumi.get(self, "password")

