// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Prevent the Domain provider from taking certain actions
func GetDryRun(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "gandi:dryRun")
}

// A Gandi API key
func GetKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "gandi:key")
}

// A Gandi Sharing ID
func GetSharingId(ctx *pulumi.Context) string {
	return config.Get(ctx, "gandi:sharingId")
}

// The Gandi API URL
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "gandi:url")
}
